-- Eliminar datos existentes en cat_segmentos
TRUNCATE TABLE cat_segmentos RESTART IDENTITY CASCADE;

INSERT INTO cat_segmentos (id_segmento, nombre, codigo, activo, created_at, updated_at) VALUES (1, 'T1 rural residencial', '001', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'T1 rural con actividad productiva', '002', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'T1G rural uso general', '003', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'T1G rural general Industrias', '004', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'T1G rural general - instituciones', '005', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'T2 - medianas demandas', 'T2-006', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'T3 - grandes demandas', 'T3-007', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'T4 - alumbrado público', '008', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'T1G - rural gen. Oficial', '009', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'T1G - rural gen. Servicios', '010', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'T1G uso comercial', '011', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'T1G uso servicios', '012', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'T1G uso general serv. Ilum. Esp', '013', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'T3 - grandes demandas s/tram', 'T3-014', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'T3 - grandes demandas Estacional', 'T3C-015', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'T2 - medianas demandas estacional', 'T2-016', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'T3 - grandes demandas produccion', 'T3-017', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'T2 - medianas demandas produccion', 'T2-018', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'T2 - medianas demandas estac -produccion', 'T2-019', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'T1 rural P TES', '020', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'T1G rural uso general industrial', '021', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'T1G rural comerc/industrial', '022', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 'T1G rural gen instit Bonif', '025', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 'T2 - medianas demandas industrias', 'T2-026', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 'T3 - grandes demandas industrias', 'T3-027', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'T1G uso general', '033', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 'T1G uso general industrial', '034', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 'T1G uso general instituciones', '035', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 'T2 - medianas demandas EXPO', 'T2-036', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 'T3 - grandes demandas mayor a 300 Kw', 'T3-037', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 'T1G - rural general oficial', '039', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 'T1G - rural general Servicios', '040', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 'T1G uso oficial', '044', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'T1G entidades de bien público', '045', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'T3 - grandes demandas ind. Mas de 300 Kw', 'T3-047', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 'T1G oficial s/tasa Mun', '055', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 'T3 - grandes demandas media tensión', 'T3-057', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 'T3 - grandes demandas media tensión mayor a 300 kW', 'T3-067', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'T1R residencial TES 1', '071', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 'T1R residencial TES 2', '072', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 'T1R residencial TES 3', '073', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 'T1G uso general industrias', '074', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 'T1G instituciones', '075', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 'T2 - medianas demandas COOP', 'T2-076', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 'T3 - grandes demandas COOP', 'T3-077', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 'Categoría sin cargo', '078', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 'T1G uso oficial', '079', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 'T1G uso general servicios', '080', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 'T1R uso residencial ahorro entre 10 y 20%', '081', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 'T1R uso residencial ahorro mas de  20%', '082', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id_segmento) DO UPDATE SET nombre = EXCLUDED.nombre, codigo = EXCLUDED.codigo, activo = EXCLUDED.activo, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cat_segmentos (id_segmento, nombre, codigo, activo, created_at, updated_at) VALUES (51, 'T1R uso residencial', '083', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 'T1R uso residencial TES 1', '084', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(53, 'T2 medianas demandas reynafé', 'T2-086', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 'T1G rural general Ind consumos > 7908', '090', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(55, 'T1G rural general consumos > 7909', '091', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 'T1G rural general consumos', '096', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(57, 'T1G rural general consumos > 7909', '097', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(58, 'T1 Ptes (tarifa eléctica social)', '098', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'T1 TEPIC dto  3485/99', '099', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(60, 'T1G uso general industrias', '181', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(61, 'T1 - Uso residencial TARIFA SOCIAL ', 'TS-U061', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(62, 'T1 - Uso RURAL residencial TARIFA SOCIAL ', 'TSR-061', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(63, 'T1R uso residencial', 'U001', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(64, 'T1G uso general', 'U003', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(65, 'T1G uso general industrias', 'U004', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(66, 'T2 medianas demandas', 'T2-U006', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(67, 'T3 grandes demandas', 'T3-U007', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(68, 'T4 - alumbrado público', 'U008', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(69, 'T1 uso comercial < 20 kW', 'U011', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(70, 'T1 uso servicios < 20 kW', 'U012', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(71, 'T1G uso general', 'U013', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(72, 'T3 grandes demandas s/reactiva', 'T3-U015', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(73, 'T2 medianas demandas estacional', 'T2C-U016', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(74, 'T3 grandes demandas produccion', 'T3-U017', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(75, 'T1 sin uso TES ', 'U020', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(76, 'T1 Uso Industrial', 'U021', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(77, 'T1 bomberos voluntarios', 'U022', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(78, 'T2 medianas demandas industrias', 'T2-U026', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(79, 'T3 grandes demandas industrias', 'T3-U027', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(80, 'T1 uso oficial < 20 kW', 'U044', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(81, 'T1 entidades bien público nacional', 'U045', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(82, 'T1 uso oficial < 20 kW - sin tasa', 'U055', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(83, 'T1 uso residencial TES 1', 'U071', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(84, 'T1 uso residencial TES 2', 'U072', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(85, 'T1 uso residencial TES 3', 'U073', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(86, 'T2 medianas demandas COOP', 'T2-U076', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(87, 'T3 grandes demandas COOP', 'T3-U077', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(88, 'T1 uso instituciones < 20 kw', 'U078', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(89, 'T1 uso instituciones clubes bonif', 'U079', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(90, 'T1 Residencial ELECTRODEPENDIENTES', 'U081', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(91, 'T1 Residencial ELECTRODEPENDIENTES', 'U082', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(92, 'T1 Residencial Tarifa para la SALUD', 'U083', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(93, 'T1G general industria consumos > 7908', 'U090', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(94, 'T1G general consumos >7908', 'U091', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(95, 'uso propio COOPERATIVA', 'U096', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(96, 'T1R SIN USO  uso residencial TES 1', 'U120', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(97, 'T1R SIN USO  uso residencial TES 2', 'U121', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(98, 'Otras ventas', 'OTV', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT (id_segmento) DO UPDATE SET nombre = EXCLUDED.nombre, codigo = EXCLUDED.codigo, activo = EXCLUDED.activo, updated_at = CURRENT_TIMESTAMP;